env:
  browser: true
  es6: true
  node: false
extends:
  - "eslint:recommended"
  - plugin:prettier/recommended
plugins:
globals:
  Atomics: readonly
  SharedArrayBuffer: readonly
parserOptions:
  ecmaVersion: 10
  sourceType: module
rules:
  no-unused-vars: warn
