---
default_language_version:
  python: python3.8
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.5.0
    hooks:
      - id: check-builtin-literals
      - id: check-merge-conflict
      - id: check-json
        exclude: "(launch|tasks)\\.json"
      - id: check-yaml
      - id: check-toml
      - id: mixed-line-ending
  - repo: https://github.com/pre-commit/pygrep-hooks
    rev: v1.5.1
    hooks:
      - id: python-check-blanket-noqa
  - repo: https://github.com/psf/black
    rev: stable
    hooks:
      - id: black
  - repo: https://gitlab.com/pycqa/flake8
    rev: 3.7.9
    hooks:
      - id: flake8
        additional_dependencies:
          - flake8-annotations
          - flake8-bugbear
          - flake8-comprehensions
          - flake8-docstrings
          - flake8-import-order
          - flake8-pytest-style
  - repo: https://github.com/prettier/prettier
    rev: 2.0.5
    hooks:
      - id: prettier
