---
default_language_version:
  python: python3.11
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: check-builtin-literals
      - id: check-merge-conflict
      - id: check-json
        exclude: '(tsconfig|launch|tasks)\.json'
      - id: check-yaml
      - id: check-toml
      - id: mixed-line-ending
      - id: check-added-large-files
  - repo: https://github.com/charliermarsh/ruff-pre-commit
    rev: v0.3.5
    hooks:
      - id: ruff
      - id: ruff-format
