version: "3.7"
services:
  holdmypics:
    image: holdmypics
    env_file: .compose.env
    build: .
    ports:
      - "4000:80"
    networks:
      - web
    depends_on:
      - redis
  redis:
    image: redis:5.0
    ports:
      - "6379:6379"
    deploy:
      placement:
        constraints: [node.role == manager]
    command: redis-server --appendonly yes
    networks:
      - web
