---
version: "3.7"
services:
  holdmypics:
    build:
      context: .
      dockerfile: config/dev/Dockerfile
    image: holdmypics-dev
    env_file: .compose.env
    ports:
      - "4000:4000"
    networks:
      - webnet
    depends_on:
      - redis
  redis:
    image: redis:5.0-alpine
    ports:
      - "6379:6379"
    deploy:
      placement:
        constraints: [node.role == manager]
    command: redis-server --appendonly yes
    networks:
      - webnet
networks:
  webnet:
