[tool.poetry]
name = "dummy-flask"
version = "0.1.0"
description = ""
authors = ["Michael Van Wickle <mvanwickle@gmail.com>"]

[tool.poetry.dependencies]
python = "^3.7"
flask = "^1.1"
pillow = "^6.1"
funcy = "^1.12"
gunicorn = { version = "^19.9", extras = ["gevent"] }
environs = "^5.1"
flask-redis = "^0.4.0"

[tool.poetry.dev-dependencies]
pytest = "^3.0"

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
