[tool.poetry]
name = "holdmypics"
version = "0.10.0"
description = ""
authors = ["Michael Van Wickle <mvanwickle@gmail.com>"]

[tool.poetry.dependencies]
python = "^3.7"
attrs = "^19.3.0"
bs4 = "^0.0.1"
environs = "^7.0"
flask = "^1.1"
flask-cors = "^3.0.8"
flask-redis = "^0.4.0"
funcy = "^1.12"
gunicorn = { version = "^20.0", extras = ["gevent"] }
humanize = "^2.0.0"
lxml = "^4.4.2"
Pillow = "^7.0.0"
redis = { version = "^3.0" }
structlog = "^20.1.0"
toml = "^0.10.0"
loguru = "^0.4.1"

[tool.poetry.dev-dependencies]
colorama = "^0.4.3"
isort = "^4.3"
psutil = "^5.6.5"
ptpython = "^3.0.0"
pytest = "^5.0"
pytest-cov = "^2.8.1"
pytest-html = "^2.0.0"
pytest-selenium = "^1.17.0"

[tool.poetry.scripts]
serve = "bin.serve:main"

[tool.isort]
known_first_party=["config", "holdmypics"]
no_lines_before="LOCALFOLDER"
multi_line_output=3
include_trailing_comma=true
force_grid_wrap=0
use_parentheses=true
line_length=88

[tool.black]
line-length = 88
skip-numeric-underscore-normalization = true
target-version = ["py38"]


[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
