[tool.poetry]
name = "holdmypics"
version = "0.15.2"
description = ""
authors = ["Michael Van Wickle <mvanwickle@gmail.com>"]

[tool.poetry.dependencies]
python = "^3.6.1"
attrs = "^19.3.0"
beautifulsoup4 = { version = "^4.3", extras = ["lxml"] }
cytoolz = "^0.10.1"
environs = "^7.0"
flask = "^1.1"
flask-cors = "^3.0.8"
flask-redis = "^0.4.0"
funcy = "^1.12"
gunicorn = { version = "^20.0" }
humanize = "^2.0.0"
loguru = "^0.4.1"
Pillow = "^7.0.0"
semver = "^2.9.1"
tomlkit = "^0.6.0"
whitenoise = { version = "^5.0.1", extras = ["brotli"] }

[tool.poetry.dev-dependencies]
colorama = "^0.4.3"
isort = "^4.3"
memory_profiler = "^0.57.0"
pre-commit = "^2.3.0"
psutil = "^5.6.5"
ptpython = "^3.0.0"
pytest = "^5.0"
pytest-cov = "^2.8.1"
pytest-html = "^2.0.0"
pytest-selenium = "^1.17.0"
toml = "^0.10.0"
pytesseract = "^0.3.4"

[tool.poetry.scripts]

[tool.poetry.plugins]

[tool.poetry.plugins."pytest11"]
holdmyplugin = "plugin.holdmyplugin"

[tool.isort]
known_first_party = ["config", "holdmypics"]
no_lines_before = "LOCALFOLDER"
multi_line_output = 3
include_trailing_comma = true
force_grid_wrap = 0
use_parentheses = true
line_length = 88

[tool.black]
line-length = 88
skip-numeric-underscore-normalization = true
target-version = ["py38"]

[tool.coverage.run]
branch = true
data_file = ".cov/.coverage"

[tool.coverage.report]
precision = 2
skip_empty = true
exclude_lines = [
    "pragma: no cover",
    "def __repr__",
    "if TYPE_CHECKING",
    "raise NotImplementedError",
    "if __name__ == .__main__.:"
]

[tool.coverage.html]
title = "Coverage Report"
directory = ".cov/htmlcov"

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
