---
version: 2.1
jobs:
  build:
    docker:
      - image: circleci/python:3.8.2
        environment:
          POETRY_VIRTUALENVS_IN_PROJECT: "1"
          POETRY_VIRTUALENVS_CREATE: "1"
      - image: circleci/redis:5.0.8-alpine
    steps:
      - checkout
      - run: sudo chown -R circleci:circleci /usr/local/bin
      - run: sudo chown -R circleci:circleci /usr/local/lib/python3.8/site-packages
      - restore_cache:
          key: deps9-{{ .Branch }}-{{ checksum "poetry.lock" }}
      - run:
          command: |
            sudo pip install poetry
            poetry install --no-interaction
      - save_cache:
          key: deps9-{{ .Branch }}-{{ checksum "poetry.lock" }}
          paths:
            - ".venv"
      - run: |
          poetry run pytest
