---
version: 2.1
jobs:
  build:
    docker:
      - image: cimg/python:3.8-node
        environment:
          POETRY_VIRTUALENVS_IN_PROJECT: "1"
          POETRY_VIRTUALENVS_CREATE: "1"
          TESTS_SKIP_INDEX: "1"
      - image: circleci/redis:6.0.8-alpine
    steps:
      - checkout
      - restore_cache:
          key: deps9-{{ .Branch }}-{{ checksum "poetry.lock" }}
      - run: sudo apt-get install tesseract-ocr libtesseract-dev
      - run:
          command: |
            pip install --user poetry
            poetry install --no-interaction -E tests
            yarn install --prod
      - save_cache:
          key: deps9-{{ .Branch }}-{{ checksum "poetry.lock" }}
          paths:
            - ".venv"
      - run: |
          poetry run pytest --no-empty-dpi
