---
version: 2.1
workflows:
  version: 2
  test:
    jobs:
      - test:
          filters:
            tags:
              only: /^v.*/
jobs:
  test:
    docker:
      - image: cimg/python:3.9-node
        environment:
          POETRY_VIRTUALENVS_IN_PROJECT: "1"
          POETRY_VIRTUALENVS_CREATE: "1"
          TESTS_SKIP_INDEX: "1"
      - image: circleci/redis:6.0.10-alpine
    steps:
      - checkout
      - restore_cache:
          key: deps9-{{ .Branch }}-{{ checksum "poetry.lock" }}
      - run:
          # yamllint disable rule:line-length
          command: |
            curl -sSL https://raw.githubusercontent.com/python-poetry/poetry/master/install-poetry.py | python - -y
            $HOME/.local/bin/poetry install --no-interaction --no-dev -E tests
            yarn install --prod
          # yamllint enable rule:line-length
      - run: |
          $HOME/.local/bin/poetry run pytest
      - save_cache:
          key: deps9-{{ .Branch }}-{{ checksum "poetry.lock" }}
          paths:
            - ".venv"
      - store_artifacts:
          path: .cache/pytest-report/report.html
          destination: pytest-report.html
      - store_artifacts:
          path: .cache/.cov/htmlcov
          destination: coverage
