---
services:
  web:
    build:
      context: .
      dockerfile: "${DOCKER_WEB_DOCKERFILE:-config/prod/Dockerfile}"
    env_file:
      - .compose.env
    ports:
      - "4000:80"
    networks:
      - webnet
    depends_on:
      - redis
  redis:
    image: redis:6.2.4-alpine
    ports:
      - "6379:6379"
    deploy:
      resources:
        limits:
          cpus: "${DOCKER_REDIS_CPUS:-0}"
          memory: "${DOCKER_REDIS_MEMORY:-0}"
      placement:
        constraints: [node.role == manager]
    command: redis-server --appendonly yes
    networks:
      - webnet
    volumes:
      - "redis:/data"
networks:
  webnet: {}
volumes:
  redis: {}
